#!/bin/bash
set -euo pipefail

# Build the system closure for each configured host, sign it, copy it into the
# nginx-served binary cache directory, and publish a manifest naming the store
# path that is now current for that host.
#
# The point is that the *client* never evaluates or builds anything: it reads
# one line of text (the store path), substitutes the closure from this cache,
# and activates it. That keeps hosts like the Wyse 3040 thin clients — 2 GiB of
# RAM, no room to evaluate this flake let alone build it — entirely out of the
# build path.

: "${FLAKE_PATH:?FLAKE_PATH not set}"
: "${CACHE_DIR:?CACHE_DIR not set}"
: "${MANIFEST_SUBDIR:?MANIFEST_SUBDIR not set}"
: "${TARGET_HOSTS:?TARGET_HOSTS not set}"
: "${SIGNING_KEY_FILE:?SIGNING_KEY_FILE not set}"
: "${SIGNING_KEY_NAME:?SIGNING_KEY_NAME not set}"
: "${RETENTION_DAYS:?RETENTION_DAYS not set}"

PUBLIC_URL="${PUBLIC_URL-}"

read -ra targetHosts <<< "$TARGET_HOSTS"
read -ra extraAttributes <<< "${EXTRA_ATTRIBUTES-}"

manifestDir="$CACHE_DIR/$MANIFEST_SUBDIR"
publicKeyFile="$SIGNING_KEY_FILE.pub"

install -d -m 0755 "$CACHE_DIR" "$manifestDir"

# Generate the cache signing key on first run. The private half never leaves
# this host; the public half is published next to the cache so clients can be
# configured with it (see `just cache-key`).
if [ ! -f "$SIGNING_KEY_FILE" ] || [ ! -f "$publicKeyFile" ]; then
    echo "Generating binary cache signing key $SIGNING_KEY_NAME"
    install -d -m 0700 "$(dirname "$SIGNING_KEY_FILE")"
    rm -f "$SIGNING_KEY_FILE" "$publicKeyFile"
    nix-store --generate-binary-cache-key "$SIGNING_KEY_NAME" "$SIGNING_KEY_FILE" "$publicKeyFile"
    chmod 0600 "$SIGNING_KEY_FILE"
fi
install -m 0444 "$publicKeyFile" "$CACHE_DIR/nix-cache-pubkey"

# Publish atomically: a client polling mid-copy must never see a path whose
# closure is only half in the cache.
publish_manifest() {
    local name="$1" path="$2"
    printf '%s\n' "$path" > "$manifestDir/.$name.tmp"
    chmod 0444 "$manifestDir/.$name.tmp"
    mv -f "$manifestDir/.$name.tmp" "$manifestDir/$name"
}

# A host that cannot evaluate this flake cannot be installed with
# `nixos-install --flake` either, and its installer ISO runs from a tmpfs
# store far smaller than the closure. So publish a script that fetches the
# already-built pieces and installs straight into /mnt, and let the operator
# run one command on the target instead of six.
publish_installer() {
    local host="$1"
    [ -n "$PUBLIC_URL" ] || return 0

    {
        printf '#!/usr/bin/env bash\n'
        printf '# Generated by closure-publisher. Do not edit here.\n'
        printf 'CACHE=%q\n' "$PUBLIC_URL"
        printf 'HOST=%q\n' "$host"
        printf 'MANIFESTS=%q\n' "$MANIFEST_SUBDIR"
        cat <<'INSTALLER'
set -euo pipefail

# This is meant to be run as `curl … | bash`, so it must not assume it owns
# stdin, and it must not assume the ISO enables nix-command by default.
NIX_COPY=(nix --extra-experimental-features nix-command copy --no-check-sigs)
assumeYes=false
if [ "${1-}" = "--yes" ]; then
    assumeYes=true
fi

fetch() { curl -fsSL --header 'Cache-Control: no-cache' "$CACHE/$MANIFESTS/$1"; }

if [ "$(id -u)" -ne 0 ]; then
    echo "Run this as root on the installer ISO." >&2
    exit 1
fi

if ! system=$(fetch "$HOST"); then
    echo "Could not read $CACHE/$MANIFESTS/$HOST — is the cache reachable?" >&2
    exit 1
fi
if ! [[ "$system" =~ ^/nix/store/[a-z0-9]{32}-.+$ ]]; then
    echo "No closure published for $HOST yet." >&2
    exit 1
fi

# Published alongside the closure when the host uses disko. Without it the
# disk has to be partitioned and mounted at /mnt by hand first.
disko=$(fetch "$HOST.diskoScript" 2>/dev/null || true)

cat <<EOF

  Host:    $HOST
  Closure: $system
  Disks:   $([ -n "$disko" ] && echo "will be ERASED and repartitioned by $disko" || echo "assumed already mounted at /mnt")

EOF
if [ "$assumeYes" != true ]; then
    # stdin is the script itself under `curl | bash`; ask the terminal.
    read -rp "Type the hostname to continue, anything else to abort: " confirm < /dev/tty
    [ "$confirm" = "$HOST" ] || { echo "Aborted."; exit 1; }
fi

if [ -n "$disko" ]; then
    # Small enough to land in the ISO's tmpfs store; the closure is not.
    "${NIX_COPY[@]}" --from "$CACHE" "$disko"
    "$disko"
fi

if ! mountpoint -q /mnt; then
    echo "/mnt is not mounted; nothing to install onto." >&2
    exit 1
fi

# Straight into the target filesystem. Copying into the ISO's own store
# first would exhaust the tmpfs on a machine with this little memory.
"${NIX_COPY[@]}" --from "$CACHE" --to /mnt "$system"
nix-env --store /mnt -p /mnt/nix/var/nix/profiles/system --set "$system"
NIXOS_INSTALL_BOOTLOADER=1 nixos-enter --root /mnt -- \
    /run/current-system/bin/switch-to-configuration boot

echo
echo "$HOST installed. Reboot, then register its SSH host key:"
echo "  ssh-keyscan -t ed25519 $HOST"
INSTALLER
    } > "$manifestDir/.$host.install.tmp"

    chmod 0444 "$manifestDir/.$host.install.tmp"
    mv -f "$manifestDir/.$host.install.tmp" "$manifestDir/$host.install"
}

# The checkout is maintained by autoUpdate under a different user; without
# this, git refuses to read it for us and the flake fetch fails.
if ! git config --global --get-all safe.directory | grep -qxF "$FLAKE_PATH"; then
    git config --global --add safe.directory "$FLAKE_PATH"
fi

failed=0

for host in "${targetHosts[@]}"; do
    echo "=== $host: building system closure"
    if ! out=$(nix build --no-link --print-out-paths \
            "$FLAKE_PATH#nixosConfigurations.$host.config.system.build.toplevel" | tail -n1); then
        echo "$host: build failed" >&2
        failed=1
        continue
    fi

    if [ -z "$out" ]; then
        echo "$host: build produced no output path" >&2
        failed=1
        continue
    fi

    echo "=== $host: signing $out"
    nix store sign --key-file "$SIGNING_KEY_FILE" --recursive "$out"

    echo "=== $host: copying closure into $CACHE_DIR"
    nix copy --to "file://$CACHE_DIR?compression=zstd&parallel-compression=true" "$out"

    publish_manifest "$host" "$out"
    echo "=== $host: published $out"

    # Additional system.build.* attributes, published as <host>.<attr>. The
    # disko script goes here: an installer booted on the target can fetch and
    # run it without evaluating anything, which is the whole point on hardware
    # that cannot evaluate this flake.
    for attr in "${extraAttributes[@]}"; do
        if ! extraOut=$(nix build --no-link --print-out-paths \
                "$FLAKE_PATH#nixosConfigurations.$host.config.system.build.$attr" | tail -n1); then
            echo "$host: $attr is not buildable, skipping" >&2
            continue
        fi
        [ -n "$extraOut" ] || continue
        nix store sign --key-file "$SIGNING_KEY_FILE" --recursive "$extraOut"
        nix copy --to "file://$CACHE_DIR?compression=zstd&parallel-compression=true" "$extraOut"
        publish_manifest "$host.$attr" "$extraOut"
        echo "=== $host: published $attr $extraOut"
    done

    publish_installer "$host"
done

# Drop cache entries that no published closure references any more. Without
# this the directory only ever grows, one full system closure per rebuild.
# Entries are only considered once they are older than RETENTION_DAYS so a
# client that started downloading the previous generation can finish.
prune_cache() {
    local live nar hash narinfo
    live=$(mktemp)
    trap 'rm -f "$live" "$live.hashes"' RETURN

    # Only the manifests that name a store path — .install is a shell script,
    # and feeding it to path-info would abort the whole prune.
    local manifest name
    for host in "${targetHosts[@]}"; do
        for name in "$host" "${extraAttributes[@]/#/$host.}"; do
            manifest="$manifestDir/$name"
            [ -f "$manifest" ] || continue
            # Bail out rather than prune on a partial view of what is live.
            if ! nix path-info --recursive "$(cat "$manifest")" >> "$live"; then
                echo "prune: could not resolve $manifest, skipping prune" >&2
                return 0
            fi
        done
    done

    sed -nE 's|^/nix/store/([a-z0-9]{32})-.*$|\1|p' "$live" | sort -u > "$live.hashes"
    if [ ! -s "$live.hashes" ]; then
        echo "prune: no live paths resolved, skipping prune" >&2
        return 0
    fi

    while IFS= read -r -d '' narinfo; do
        hash=$(basename "$narinfo" .narinfo)
        if grep -qxF "$hash" "$live.hashes"; then
            continue
        fi
        nar=$(awk '/^URL: /{print $2; exit}' "$narinfo")
        rm -f "$narinfo"
        if [ -n "$nar" ]; then
            rm -f "$CACHE_DIR/$nar"
        fi
    done < <(find "$CACHE_DIR" -maxdepth 1 -type f -name '*.narinfo' -mtime "+$RETENTION_DAYS" -print0)
}

if [ "$RETENTION_DAYS" -ge 0 ]; then
    prune_cache
fi

exit "$failed"
