#!/usr/bin/env -S just --justfile
set fallback

_test_vm machine:
    @echo "Testing a vm is still needed {{machine}}"

sierra: && (_test_vm "sierra-2")

delta:
    @echo "Raspberry Pi 4 images can't be run in a VM yet"
    mkdir -p {{justfile_directory()}}/test/working/delta
    zstd -d {{justfile_directory()}}/result/sd-image/*.img.zst -o {{justfile_directory()}}/test/working/delta/sd-card.img
    