# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, config, lib, modulesPath, pkgs,... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
      inputs.nixos-hardware.nixosModules.common-gpu-intel
      inputs.nixos-hardware.nixosModules.common-cpu-amd
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "mpt3sas" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/a8500844-3dc2-4ac0-b443-adf3d75b512c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/6D58-A60D";
      fsType = "vfat";
    };

  boot = {
    kernelPackages = pkgs.linuxPackages_6_17;
    zfs = {
      extraPools = [ "vault" "scary" ];
      forceImportRoot = false;
      devNodes = "/dev/disk/by-partlabel";
    };
  };
  services.zfs.autoScrub.enable = true;

  swapDevices = [ ];

  hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;
  hardware.intelgpu.driver = "i915";
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [ level-zero ];
  };

  boot.kernelParams = [ 
    "i915.enable_guc=3"        # Enable GuC for both submission and HuC loading
    "i915.force_probe=56a5"    # Force probe your specific Arc A380 device ID
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp11s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  networking.hostId = "aa99924f";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
