---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: Nelson Family
  navLinks:
  - title: GitHub
    path: https://github.com/bcnelson

# Optional app settings and configuration
appConfig:
  theme: colorful
  disableConfiguration: true
  websearch:
    searchEngine: google
    openingMethod: 'sametab'
    searchBangs:
      /np: 'https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query='
      /nixos: "https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query="
      /nixpkgs: "https://sourcegraph.com/search?patternType=standard&sm=1&q=context:global+repo:^github\\.com/NixOS/nixpkgs%24+"

# Main content - An array of sections, each containing an array of items
sections:
  - name: Nix
    icon: mdi-nix
    items:
    - title: NixPkgs Search
      description: Development a project management links for Dashy
      icon: mdi-search-web
      url: https://search.nixos.org/packages
      target: newtab
  - name: Media
    icon: mdi-multimedia
    items:
      - title: Jellyfin
        description: Media server
        icon: mdi-server
        url: https://media.nel.family
        target: newtab
      - title: AudioBooks
        description: AudioBooks
        icon: mdi-bookshelf
        url: https://audiobooks.nel.family
  - name: Home
    icon: mdi-home
    items:
      - title: Home Assistant
        description: Home Automation
        icon: mdi-home-assistant
        url: https://homeassistant.h.b.nel.family
      - title: Inventory
        description: Homebox
        icon: mdi-clipboard
        url: https://homebox.nel.family
      - title: Todo
        description: Todo
        icon: mdi-checkbox-marked-circle-auto-outline
        url: https://todo.nel.family
