[package]
name = "nix-cache-discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait="0.1"
pingora = { version = "0.4", features = [ "lb", "openssl" ] }
pingora-core = "0.4"
pingora-load-balancing = "0.4"
pingora-proxy = "0.4"
url = "2.5.4"
log = "0.4"
simplelog = "0.12"
mdns-sd = "0.13.2"
tokio = "1.43.0"


[[bin]]
name = "client"
path = "src/main.rs"

