# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8591db6c-cbcb-48a7-8c40-62eafe85d985";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0A47-84FE";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Alder Lake-P Iris Xe: VA-API hardware decode (needed by moonlight-qt, mpv, browsers).
  # Mesa alone ships no Intel VA-API driver, so vaInitialize fails without iHD.
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      intel-media-driver # iHD, Broadwell (2014) or newer
      vpl-gpu-rt # oneVPL runtime for Gen12+
    ];
  };
  environment.systemPackages = [ pkgs.libva-utils ]; # vainfo, for verifying decode support

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  services.bcnelson.autoUpdate = {
    path = lib.mkForce "/config";
  };
}
