//! Installing hosts that cannot install themselves.
//!
//! The normal path ends in `nixos-install --flake .#host`, which evaluates
//! this flake and builds the closure on the target. Some hardware cannot do
//! either — a Dell Wyse 3040 has 2 GiB of RAM, and evaluating this flake
//! needs more than that before a single derivation is built.
//!
//! A limited install does everything else the same way: it clones the repo,
//! unlocks it, partitions the disk, generates the hardware configuration and
//! the SSH host key, and commits them. Then, instead of building, it pushes
//! the branch, opens a pull request, and waits for the builder to publish the
//! closure (see services.bcnelson.closurePublisher). When the closure appears
//! it is copied straight from the cache into /mnt and activated, following
//! nixos-install's remaining steps.

use anyhow::{anyhow, bail, Context, Result};
use cmd_lib::{run_cmd, run_fun};
use std::io::Write;
use std::thread;
use std::time::{Duration, Instant};

const REPO: &str = "BCNelson/nix-config";
const POLL_INTERVAL: Duration = Duration::from_secs(30);

/// Push the install branch and open a pull request for it.
///
/// Merging is left to a human on purpose: the branch carries a hardware scan
/// and an SSH host key from a machine that has just been wiped, and the
/// secrets still need rekeying with a hardware key the target does not have.
pub fn push_and_open_pr(host: &str, branch: &str) -> Result<()> {
    run_cmd!(
        git config push.autoSetupRemote true;
        just push;
        git config --unset push.autoSetupRemote;
    )?;
    println!("Pushed {branch}");

    match open_pull_request(host, branch) {
        Ok(url) => println!("Opened {url}"),
        Err(e) => {
            println!("Could not open a pull request automatically: {e}");
            println!("Open one for {branch} against main by hand.");
        }
    }
    Ok(())
}

fn github_token() -> Result<String> {
    // Same source `just push` uses; the repo is already unlocked by now.
    let raw = run_fun!(nix eval --file ./nixos/sensitive.nix gh_token)
        .context("reading gh_token from nixos/sensitive.nix")?;
    let token = raw.trim().trim_matches('"').to_string();
    if token.is_empty() {
        bail!("gh_token is empty");
    }
    Ok(token)
}

fn open_pull_request(host: &str, branch: &str) -> Result<String> {
    let token = github_token()?;
    let auth = format!("Authorization: Bearer {token}");
    let url = format!("https://api.github.com/repos/{REPO}/pulls");

    let payload = serde_json::json!({
        "title": format!("Install {host}"),
        "head": branch,
        "base": "main",
        "body": format!(
            "Generated by `install-system --limited` for `{host}`.\n\n\
             Carries its hardware scan, SSH host key, flake entry and \
             registration with the closure builder.\n\n\
             **Run `just rekey` before merging.** The installer cannot: \
             rekeying evaluates every host, and this machine cannot evaluate \
             the flake at all — which is why it is a limited host in the \
             first place.\n\n\
             Once this is on main the builder publishes `{host}`'s closure, \
             and the installer waiting on the target picks it up."
        ),
    })
    .to_string();

    let response = run_fun!(
        curl --fail --silent --show-error
            -X POST
            -H "Accept: application/vnd.github+json"
            -H $auth
            -d $payload
            $url
    )
    .context("calling the GitHub pulls API")?;

    let parsed: serde_json::Value =
        serde_json::from_str(&response).context("parsing GitHub's response")?;
    parsed
        .get("html_url")
        .and_then(|v| v.as_str())
        .map(str::to_string)
        .ok_or_else(|| anyhow!("no html_url in GitHub's response: {response}"))
}

/// Poll the builder's manifest until it names a closure for this host.
pub fn wait_for_closure(cache: &str, host: &str, wait_minutes: u64) -> Result<String> {
    let deadline = Instant::now() + Duration::from_secs(wait_minutes * 60);

    println!();
    println!("Waiting for the builder to publish {host}'s closure.");
    println!("  Merge the pull request; this polls {cache}/system/{host}");
    println!("  and gives up after {wait_minutes} minutes.");

    loop {
        if let Some(path) = published_closure(cache, host) {
            println!();
            println!("Published: {path}");
            return Ok(path);
        }
        if Instant::now() >= deadline {
            bail!("gave up after {wait_minutes} minutes waiting for {host}'s closure");
        }
        print!(".");
        std::io::stdout().flush().ok();
        thread::sleep(POLL_INTERVAL);
    }
}

/// `None` rather than an error when nothing valid is published, so the wait
/// loop can tell "not yet" from "broken". A missing manifest is answered by
/// the cache's upstream fallback, so an unexpected body means "not
/// published", not "here is a store path".
fn published_closure(cache: &str, host: &str) -> Option<String> {
    let url = format!("{cache}/system/{host}");
    let response = run_fun!(
        curl --fail --silent --location --header "Cache-Control: no-cache" $url
    )
    .ok()?;

    let path = response.lines().next()?.trim().to_string();
    if is_store_path(&path) {
        Some(path)
    } else {
        None
    }
}

fn is_store_path(path: &str) -> bool {
    let Some(rest) = path.strip_prefix("/nix/store/") else {
        return false;
    };
    let Some((hash, name)) = rest.split_once('-') else {
        return false;
    };
    hash.len() == 32
        && hash.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
        && !name.is_empty()
}

/// Install a closure that was built elsewhere.
///
/// This is nixos-install minus the build: the same profile, marker file,
/// mtab and chroot handling, because leaving any of them out produces a
/// target that looks installed and will not boot.
pub fn install_closure(cache: &str, system: &str) -> Result<()> {
    // nix's temporary files must not land on the installer's tmpfs — that is
    // RAM, and on these machines there is not enough of it to unpack a system
    // closure into. nixos-install puts them on the target for the same reason.
    let tmpdir = run_fun!(sudo mktemp -d -p /mnt).context("creating a temporary directory on /mnt")?;

    println!("Copying the closure into /mnt");
    run_cmd!(sudo env TMPDIR=$tmpdir nix --extra-experimental-features "nix-command" copy --no-check-sigs --from $cache --to /mnt $system)
        .context("copying the closure into /mnt")?;

    verify_fstab_devices(system)?;

    run_cmd!(sudo nix-env --store /mnt -p /mnt/nix/var/nix/profiles/system --set $system)
        .context("setting the system profile")?;

    // Without /etc/NIXOS switch-to-configuration refuses to touch the target,
    // and the install finishes with a populated store and no bootloader.
    // Bootloader installers want an mtab.
    run_cmd!(
        sudo mkdir -m 0755 -p /mnt/etc;
        sudo touch /mnt/etc/NIXOS;
        sudo ln -sfn /proc/mounts /mnt/etc/mtab;
    )
    .context("marking /mnt as a NixOS installation")?;

    // The rbind/rslave dance is nixos-install's: it keeps every mount point
    // reachable at its absolute path from inside the chroot, which bootloader
    // installation depends on.
    let enter = r#"set -e
hash -r
mount --rbind --mkdir / "$mountPoint"
mount --make-rslave "$mountPoint"
/run/current-system/bin/switch-to-configuration boot
umount -R "$mountPoint" && (rmdir "$mountPoint" 2>/dev/null || true)"#;

    println!("Installing the boot loader");
    run_cmd!(sudo env NIXOS_INSTALL_BOOTLOADER=1 mountPoint=/mnt nixos-enter --root /mnt -c $enter)
        .context("installing the boot loader")?;

    run_cmd!(sudo rm -rf $tmpdir).ok();
    Ok(())
}

/// Check that the devices the closure expects are the devices we just made.
///
/// A limited closure is built before its disk exists, so until now nothing
/// has compared the two. Catching it here costs a second; catching it after
/// the reboot means an emergency shell on a machine that cannot rebuild
/// itself.
fn verify_fstab_devices(system: &str) -> Result<()> {
    // $system/etc is a symlink to an absolute store path, which on the
    // installer resolves against the wrong root. Follow it by hand.
    let etc_link = format!("/mnt{system}/etc");
    let Ok(etc_target) = std::fs::read_link(&etc_link) else {
        println!("No /etc in the closure to check devices against; skipping");
        return Ok(());
    };
    let fstab = format!("/mnt{}/fstab", etc_target.display());
    let Ok(contents) = std::fs::read_to_string(&fstab) else {
        println!("No fstab in the closure to check devices against; skipping");
        return Ok(());
    };

    let missing: Vec<String> = contents
        .lines()
        .filter(|line| !line.trim_start().starts_with('#'))
        .filter_map(|line| line.split_whitespace().next())
        .filter(|device| device.starts_with("/dev/"))
        .filter(|device| !std::path::Path::new(device).exists())
        .map(str::to_string)
        .collect();

    if !missing.is_empty() {
        bail!(
            "the closure expects devices that do not exist: {}\n\
             The partitioning does not match the configuration. Do not reboot; \
             fix the disko config, republish, and re-run.",
            missing.join(", ")
        );
    }

    println!("Every device in the closure's fstab exists");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

        #[test]
    fn recognises_store_paths() {
        assert!(is_store_path(
            "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-nixos-system-delta-1-26.05"
        ));
        // An HTML error page from the cache's upstream fallback.
        assert!(!is_store_path("<!DOCTYPE html>"));
        assert!(!is_store_path(""));
        // Truncated hash.
        assert!(!is_store_path("/nix/store/aaaa-nixos-system"));
        // Hash but no name.
        assert!(!is_store_path(
            "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-"
        ));
        // Uppercase is not nix's base32 alphabet.
        assert!(!is_store_path(
            "/nix/store/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-nixos-system"
        ));
    }
}
