server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name cache.h.b.nel.family;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    set $upstream_endpoint http://cache.nixos.org;

    proxy_cache_path /tmp/pkgcache levels=1:2 keys_zone=cachecache:100m max_size=20g inactive=365d use_temp_path=off;
      
    # Cache only success status codes; in particular we don't want to cache 404s.
    # See https://serverfault.com/a/690258/128321
    map $status $cache_header {
        200     "public";
        302     "public";
        default "no-cache";
    }

    location @fallback {
        include /config/nginx/proxy.conf;
        proxy_pass $upstream_endpoint$request_uri;
        proxy_cache cachecache;
        proxy_cache_valid  200 302  60d;
        expires max;
        add_header Cache-Control $cache_header always;
    }

    location /nix-cache-info {
        include /config/nginx/proxy.conf;
        proxy_pass $upstream_endpoint;
        proxy_cache cachecache;
        proxy_cache_valid  200 302  60d;
        expires max;
        add_header Cache-Control $cache_header always;
    }
}
