name: Nix Flake Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - '**.nix'
      - '**.age'
      - '.github/workflows/check.yml'
  push:
    branches:
      - 'main'
    paths:
      - '**.nix'
      - '**.age'
      - '.github/workflows/check.yml'
  workflow_dispatch:

jobs:
  check-hosts:
    uses: ./.github/workflows/check-nix-config.yml
  
  auto-update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: check-hosts
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update auto-update branch
        run: |
          git checkout -b auto-update && git reset --hard origin/main && git push origin auto-update -f || {
            echo "Failed to update auto-update branch"
            exit 1
          }
      - name: Send notification
        run: |
          curl -d "Github Actions Update" ntfy.sh/${{ secrets.NTFY_UPDATE_TOPIC }} || {
            echo "Failed to send notification"
            exit 1
          }