name: Bump flake.lock

on:
  pull_request:
    paths:
      - '**.nix'
      - '.github/workflows/check.yml'
  push:
    branches:
      - 'main'
    paths:
      - '**.nix'
      - '.github/workflows/check.yml'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - run: nix flake check
