name: Apply Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - "*.tf"
      - ".github/workflows/terraform.yml"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.B2_TERRAFORM_STATE_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_TERRAFORM_STATE_APPLICATION_KEY }}
        run: terraform init
      - name: Terraform Plan
        env:
            TF_VAR_porkbun_api_key: ${{ secrets.PORKBUN_API_KEY }}
            TF_VAR_porkbun_secret_key: ${{ secrets.PORKBUN_SECRET_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.B2_TERRAFORM_STATE_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_TERRAFORM_STATE_APPLICATION_KEY }}
        run: terraform plan -out=tfplan
      - name: Terraform Apply
        env:
            TF_VAR_porkbun_api_key: ${{ secrets.PORKBUN_API_KEY }}
            TF_VAR_porkbun_secret_key: ${{ secrets.PORKBUN_SECRET_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.B2_TERRAFORM_STATE_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_TERRAFORM_STATE_APPLICATION_KEY }}
        run: terraform apply tfplan