name: Bump flake.lock

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  schedule:
    - cron: "0 9 * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix flake update

      - uses: actions/upload-artifact@v4
        with:
          name: flake.lock
          path: ./flake.lock

  check-hosts:
    needs: update
    uses: ./.github/workflows/check-hosts.yml
    with:
      updated_flake: true

  comment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: check-hosts
    permissions:
      contents: write
      id-token: write
      actions: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: rm -f flake.lock
      - uses: actions/download-artifact@v4
        id: download-artifact
        with:
          name: flake.lock

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot # defaults to "GitHub Actions"
          #commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Flake Bot <actions@github.com> # defaults to author of the commit that triggered the run
          skip_dirty_check: false    
          skip_fetch: true

      - name: Update auto-update branch
        run: |
          git checkout -b auto-update && git reset --hard origin/main && git push origin auto-update -f || {
            echo "Failed to update auto-update branch"
            exit 1
          }
      - name: Send notification
        run: |
          curl -d "Github Actions Update" ntfy.sh/${{ secrets.NTFY_UPDATE_TOPIC }} || {
            echo "Failed to send notification"
            exit 1
          }
