name: Bump flake.lock

on:
  schedule:
    - cron: "0 9 * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix flake update

      - uses: actions/upload-artifact@v4
        with:
          name: flake.lock
          path: ./flake.lock

  get-hosts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      hosts: ${{ steps.set-hosts.outputs.hosts }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - id: set-hosts
        run: echo "hosts=$(nix eval .#nixosConfigurations --apply builtins.attrNames --json)" >> $GITHUB_OUTPUT

  check-hosts:
    needs: 
      - get-hosts
      - update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ${{ fromJson(needs.get-hosts.outputs.hosts) }}
      fail-fast: false
    permissions:
      contents: read
      id-token: write
      actions: read
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/download-artifact@v4
        with:
          name: flake.lock
          path: ./flake.lock
      - name: Check host ${{ matrix.host }}
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --dry-run

  comment:
    runs-on: ubuntu-latest
    needs: check-hosts
    permissions:
      contents: write
      id-token: write
      actions: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: actions/download-artifact@v4
        with:
          name: flake.lock
          path: ./flake.lock

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot # defaults to "GitHub Actions"
          #commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Flake Bot <actions@github.com> # defaults to author of the commit that triggered the run
          skip_dirty_check: false    
          skip_fetch: true

      - run: git checkout -b auto-update && git reset --hard origin/main && git push origin auto-update -f
      - run: curl -d "Github Actions Update" ntfy.sh/${{ secrets.NTFY_UPDATE_TOPIC }}
